import {useEffect,useRef} from 'react';
import {FiChevronLeft,FiChevronRight,FiClock,FiHeart,FiPlay,FiStar,FiX} from 'react-icons/fi';
export function VideoModal({item,user,onAction,onProgress,onClose}){
 const ref=useRef(null);
 const latest=useRef(user.videoProgress[item?.id]||0);
 useEffect(()=>()=>{if(item&&ref.current){const v=ref.current;const value=v.duration?Math.min(1,v.currentTime/v.duration):latest.current;onProgress?.(item.id,value,true)}},[item,onProgress]);
 if(!item)return null;
 const p=user.videoProgress[item.id]||0;
 const save=immediate=>{const v=ref.current;if(!v||!v.duration)return;const value=Math.max(0,Math.min(1,v.currentTime/v.duration));latest.current=value;onProgress?.(item.id,value,immediate)};
 return <div className="modal-bg open" onClick={e=>e.target===e.currentTarget&&onClose()}><div className="modal"><div className="modal-head"><div className="modal-title">{item.name}</div><button className="modal-close" onClick={onClose} aria-label="Close"><FiX/></button></div><div className="modal-video-wrap"><video ref={ref} src={item.src} controls autoPlay onLoadedMetadata={e=>{if(p>0&&p<.95)e.currentTarget.currentTime=e.currentTarget.duration*p}} onTimeUpdate={e=>save(false)} onPause={()=>save(true)} onEnded={()=>{const v=ref.current;if(v){latest.current=1;onProgress?.(item.id,1,true)}}}/></div><div className="modal-footer"><button className={'modal-act-btn '+(user.liked.includes(item.id)?'on-like':'')} onClick={()=>onAction('liked',item.id)}><FiHeart/> Like</button><button className={'modal-act-btn '+(user.favorites.includes(item.id)?'on-fav':'')} onClick={()=>onAction('favorites',item.id)}><FiStar/> Favorite</button><button className={'modal-act-btn '+(user.watchLater.includes(item.id)?'on-later':'')} onClick={()=>onAction('watchLater',item.id)}><FiClock/> Later</button><div className="modal-stars">{[1,2,3,4,5].map(n=><button key={n} className={'star-btn '+(n<=(user.ratings[item.id]||0)?'on':'')} onClick={()=>onAction('rating',item.id,n)}>★</button>)}</div></div></div></div>
}
export function Lightbox({items,index,user,onAction,onClose,setIndex}){const item=items[index];useEffect(()=>{const k=e=>{if(e.key==='Escape')onClose();if(e.key==='ArrowLeft')setIndex((index-1+items.length)%items.length);if(e.key==='ArrowRight')setIndex((index+1)%items.length)};window.addEventListener('keydown',k);return()=>window.removeEventListener('keydown',k)},[index,items.length]);if(!item)return null;return <div className="lightbox open" onClick={e=>e.target===e.currentTarget&&onClose()}><button className="lb-close-btn" onClick={onClose} aria-label="Close"><FiX/></button><img className="lb-img" src={item.src} alt={item.name}/><div className="lb-bar"><button className="lb-nav" onClick={()=>setIndex((index-1+items.length)%items.length)}><FiChevronLeft/></button><button className={'modal-act-btn '+(user.favorites.includes(item.id)?'on-fav':'')} onClick={()=>onAction('favorites',item.id)}><FiStar/></button><button className={'modal-act-btn '+(user.liked.includes(item.id)?'on-like':'')} onClick={()=>onAction('liked',item.id)}><FiHeart/></button><div className="lb-info">{item.name} — {index+1}/{items.length}</div><button className="lb-nav" onClick={()=>setIndex((index+1)%items.length)}><FiChevronRight/></button></div></div>}
