
export const PROJECTS = [
  {
    slug: "code-forge",
    title: "Code Forge",
    tags: ["React", "Node.js", "MongoDB"],
    contribution: "A browser-based development workspace and VS Code-inspired web application.",
    coverLabel: "CODE FORGE",
    site: { url: "https://code-forge-gamma.vercel.app", label: "Live" },
    repo: "https://github.com/SaurabhArt111/CodeForge",
  },
  {
    slug: "drift-x-commune",
    title: "Drift X Commune",
    tags: ["React", "Booking", "Admin"],
    contribution: "A premium motorsports and gaming booking experience with management tools.",
    coverLabel: "DRIFT X COMMUNE",
    site: { url: "https://driftxcommune.com", label: "Live" },
  },
  {
    slug: "game-center-management",
    title: "Game Center Management",
    tags: ["Dashboard", "Operations", "MERN"],
    contribution: "A game-center management and control system for operational workflows.",
    coverLabel: "GAME CENTER MANAGEMENT",
    site: { url: "https://driftxcommune.com", label: "Live" },
    repo: "https://github.com/SaurabhArt111/Game-Center",
  },
  {
    slug: "dynamic-qr",
    title: "Dynamic QR",
    tags: ["React", "QR", "Utility"],
    contribution: "A dynamic QR management application built for practical everyday use.",
    coverLabel: "DYNAMIC QR",
    site: { url: "https://dynamicqr-iota.vercel.app/", label: "Live" },
  },
  {
    slug: "compressor",
    title: "Compressor",
    tags: ["Media", "Web App", "UX"],
    contribution: "A web application for compressing and handling digital media.",
    coverLabel: "COMPRESSOR",
  },
  {
    slug: "lan-chat",
    title: "LAN-CHAT",
    tags: ["Realtime", "Chat", "MERN"],
    contribution: "A local network communication application with a modern chat interface.",
    coverLabel: "LAN-CHAT",
    repo: "https://github.com/SaurabhArt111/LAN-CHAT",
  },
  {
    slug: "attendance-hub",
    title: "Attendance Hub",
    tags: ["SaaS", "HR", "Dashboard"],
    contribution: "An employee attendance and management web application.",
    coverLabel: "ATTENDANCE HUB",
    site: { url: "https://attendancehub-saas.vercel.app", label: "Live" },
  },
  {
    slug: "movie-booking",
    title: "Movie Booking",
    tags: ["PHP", "MySQL", "Booking"],
    contribution: "A PHP-based movie booking application with database-backed workflows.",
    coverLabel: "MOVIE BOOKING",
    repo: "https://github.com/SaurabhArt111/Movie_booking_php",
  },
  {
    slug: "event-planner",
    title: "Event Planner",
    tags: ["MERN", "Events", "Planning"],
    contribution: "A web application for planning and managing events.",
    coverLabel: "EVENT PLANNER",
    repo: "https://github.com/SaurabhArt111/Event-Planner",
  },
  {
    slug: "quiz-show",
    title: "Quiz Show",
    tags: ["Games", "MERN", "Admin"],
    contribution: "A web application for hosting and managing quiz competitions.",
    coverLabel: "QUIZ SHOW",
    repo: "https://github.com/SaurabhArt111/Quiz_Show",
  }
];
